name: Run tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.OS }} - Py${{ matrix.PYTHON_VERSION }}
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false 
      matrix:
        OS: ['ubuntu-latest', 'windows-latest']
        PYTHON_VERSION: ['3.5', '3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}
    - name: Install test dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install .[test]
        pip install codecov
    - name: Install nbformat
      run: |
        pip install .
        pip freeze
    - name: List dependencies
      run: |
        pip list
    - name: Run tests
      run: |
        py.test nbformat/tests -v --cov=nbformat
    - name: Check manfest
      run: |
        check-manifest -v
    - name: Coverage
      run: |
        codecov
